/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bdd;


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrea
 */
public class Personnel extends javax.swing.JFrame {

    
    //Variable
    RequeteSQL requete = new RequeteSQL();
    ConnexionBDD connecter = new ConnexionBDD();
    private Connection conn;
    DefaultTableModel tableau;
    /**
     * Creates new form Personnel
     */
    public Personnel() {
        initComponents();
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPersonnel = new javax.swing.JPanel();
        panelEntete = new javax.swing.JPanel();
        labelTitre = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnActualiser = new javax.swing.JButton();
        labelNom = new javax.swing.JLabel();
        labelPrenom = new javax.swing.JLabel();
        labelMail = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        labelAdresse = new javax.swing.JLabel();
        labelFontion = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        selectFonction = new javax.swing.JComboBox<>();
        txtMail = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabPersonnel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelTitre.setText("Personnel");

        btnAjouter.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSupprimer.setText("Supprimer");

        btnActualiser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnActualiser.setText("Actualiser");
        btnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEnteteLayout = new javax.swing.GroupLayout(panelEntete);
        panelEntete.setLayout(panelEnteteLayout);
        panelEnteteLayout.setHorizontalGroup(
            panelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnteteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitre)
                .addGap(31, 31, 31)
                .addComponent(btnAjouter)
                .addGap(18, 18, 18)
                .addComponent(btnModifier)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimer)
                .addGap(18, 18, 18)
                .addComponent(btnActualiser)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelEnteteLayout.setVerticalGroup(
            panelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnteteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitre)
                    .addGroup(panelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAjouter)
                        .addComponent(btnModifier)
                        .addComponent(btnSupprimer)
                        .addComponent(btnActualiser)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        labelNom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNom.setText("Nom");

        labelPrenom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPrenom.setText("Prénom");

        labelMail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMail.setText("Mail");

        labelTel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTel.setText("Téléphone");

        labelAdresse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelAdresse.setText("Adresse");

        labelFontion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelFontion.setText("Fonctions");

        txtNom.setBackground(new java.awt.Color(255, 255, 255));

        txtPrenom.setBackground(new java.awt.Color(255, 255, 255));

        selectFonction.setBackground(new java.awt.Color(255, 255, 255));
        selectFonction.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        selectFonction.setForeground(new java.awt.Color(0, 0, 0));
        selectFonction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choix", "Administrateur", "Responsable", "Technicien", "Employé" }));

        txtMail.setBackground(new java.awt.Color(255, 255, 255));

        txtTel.setBackground(new java.awt.Color(255, 255, 255));

        txtAdresse.setBackground(new java.awt.Color(255, 255, 255));

        TabPersonnel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Mail", "Téléphone", "Adresse", "Métier"
            }
        ));
        jScrollPane1.setViewportView(TabPersonnel);

        javax.swing.GroupLayout panelPersonnelLayout = new javax.swing.GroupLayout(panelPersonnel);
        panelPersonnel.setLayout(panelPersonnelLayout);
        panelPersonnelLayout.setHorizontalGroup(
            panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEntete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPersonnelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonnelLayout.createSequentialGroup()
                        .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonnelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTel)))
                            .addGroup(panelPersonnelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrenom)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFontion)
                                    .addComponent(selectFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPersonnelLayout.createSequentialGroup()
                        .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAdresse)
                            .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelPersonnelLayout.setVerticalGroup(
            panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonnelLayout.createSequentialGroup()
                .addComponent(panelEntete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNom)
                    .addComponent(labelPrenom)
                    .addComponent(labelFontion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMail)
                    .addComponent(labelTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPersonnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        if (checkEmptyField()) {
            JOptionPane.showMessageDialog(null, "Les informations ne sont pas correctement complétées", "Information manquante", JOptionPane.ERROR_MESSAGE);
        }else{
            conn = connecter.connBdd();
            requete.AjoutePersonnel(txtNom.getText(), txtPrenom.getText(), txtAdresse.getText(), txtMail.getText(), txtTel.getText(), selectFonction.getSelectedIndex(), conn);
            connecter.deconnBdd(conn);
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserActionPerformed
        //permet de remttre les cases vides
        txtNom.setText("");
        txtPrenom.setText("");
        txtAdresse.setText("");
        txtMail.setText("");
        txtTel.setText("");
    }//GEN-LAST:event_btnActualiserActionPerformed

    private boolean checkEmptyField(){
        //Check si vide ou pas
        return (txtNom.getText().equals("") || txtPrenom.getText().equals("") || txtAdresse.getText().equals("") ||
                txtMail.getText().equals("") || txtTel.getText().equals(""));
    }
    
     public void Table() {
        String[] User = {"Nom", "Prénom", "Mail", "Téléphone", "Adresse", "Fonction"};
        String[] Monter = new String[6];

        tableau = new DefaultTableModel(null, User);

        try {
            conn = connecter.connBdd();
            ResultSet rs = requete.Tableau("select Nom, Prenom, Mail, Tel, Adresse, Metier from personnel, fonction where personnel.IDFonction = fonction.IDFonction", conn);
            while (rs.next()) {
                Monter[0] = rs.getString("Nom");
                Monter[1] = rs.getString("Prenom");
                Monter[2] = rs.getString("Mail");
                Monter[3] = rs.getString("Tel");
                Monter[4] = rs.getString("Adresse");
                Monter[5] = rs.getString("Metier");
                tableau.addRow(Monter);
            }
            TabPersonnel.setModel(tableau);
            conn.close();
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personnel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabPersonnel;
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdresse;
    private javax.swing.JLabel labelFontion;
    private javax.swing.JLabel labelMail;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JLabel labelTel;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JPanel panelEntete;
    private javax.swing.JPanel panelPersonnel;
    private javax.swing.JComboBox<String> selectFonction;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
